### ISSUE TITLE
Eww-Bar doesn't work when clicked

### ISSUE THREAD

**Issue by radstevee** [NightCS/nightlypwn#1]
So yeah, when I click on the app icons (that are always grey) nothing happens. The other buttons work. Also is there a way to make the bar be on the bottom of the screen? thanks

Note: bspc query -D -d --names always gives Desktop

**Comment by AlphaTechnolog** [comment]
Did you have a custom `bspwmrc`? or the files that you use is from the repository?
> Note: Is necesary your workspaces will be `1 2 3 4 5 6 7 8 9 X` (`bspc monitor primary -d 1 2 3 4 5 6 7 8 9 X`), to make the workspaces script works

**Comment by radstevee** [comment]
Closed because it fucked my installation and i reinstalled with plasma
